services:
    frontend:
        depends_on:
            - backend
        build:
            context: .
            dockerfile: ./deployment/frontend.Dockerfile
        restart: always
        ports:
            - '80:80'
            - '3000:3000'
    backend:
        depends_on:
            redis:
                condition: service_healthy
        build:
            context: .
            dockerfile: ./deployment/backend.Dockerfile
        restart: always
    redis:
        image: redis:latest
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 1s
            timeout: 3s
            retries: 5
        command: ['redis-server']
